# Generated by Django 3.2.4 on 2021-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='faculty')),
                ('instagram', models.URLField(default='http://google.com', max_length=300)),
                ('github', models.URLField(default='http://google.com', max_length=300)),
                ('linkedin', models.URLField(default='http://google.com', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nameoncard', models.CharField(max_length=50)),
                ('creditcardnumber', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cvv', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
    ]
